version: '3.7'
services:
  app:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - app-data:/var/www/html
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ultraxi
    volumes:
      - db-data:/var/lib/mysql

volumes:
  app-data:
  db-data:
